package com.setec.resource.domain;

public enum FileType {
    LOGIN,REGISTER,OTP,PROFILE,SURVEY,QR,FRGPWD,DEFAULT,
    BGLOGIN,BGREGISTER,BGOTP,BGPROFILE,BGSURVEY,BGQR,BGFRGPWD,BGDEFAULT,ICON,AVATAR
}
